### ISSUE TITLE
yolov7 train error

### ISSUE THREAD

**Issue by coderonion** [jizhishutong/YOLOU#14]
![Screenshot 2022-07-30 10:12:59](https://user-images.githubusercontent.com/99076655/181866383-801f2845-3a94-4345-8394-3b2b81320382.png)

![Screenshot 2022-07-30 10:12:17](https://user-images.githubusercontent.com/99076655/181866387-ae0107b8-17ae-4d2a-b1e8-1c8057094a4a.png)

**Comment by abcc235** [comment]
Starting training for 100 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/190 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 771, in <module>
    main(opt)
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 669, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 449, in train
    loss, loss_items = compute_loss(pred, targets.to(device))
TypeError: __call__() missing 1 required positional argument: 'imgs'

**Comment by jizhishutong** [comment]
If You want to train Yolov7, You need set use_aux as True.


---- Replied Message ----
| From | ***@***.***> |
| Date | 7/30/2022 10:14 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [jizhishutong/YOLOU] yolov7 train error (Issue #14) |

**Comment by jizhishutong** [comment]
If You want to train Yolov7, You need set use_aux as True.



---- Replied Message ----
| From | ***@***.***> |
| Date | 8/1/2022 15:09 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [jizhishutong/YOLOU] yolov7 train error (Issue #14) |

Starting training for 100 epochs...

 Epoch   gpu_mem       box       obj       cls    labels  img_size


0%| | 0/190 [00:05<?, ?it/s]
Traceback (most recent call last):
File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 771, in
main(opt)
File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 669, in main
train(opt.hyp, opt, device, callbacks)
File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 449, in train
loss, loss_items = compute_loss(pred, targets.to(device))
TypeError: call() missing 1 required positional argument: 'imgs'

**Comment by abcc235** [comment]
> use_aux

   
![Uploading image.png…]()



  Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/190 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 771, in <module>
    main(opt)
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 669, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 447, in train
    loss, loss_items = compute_loss(pred, targets.to(device), imgs)  # init loss class
  File "/home/hanrenkun/F/test/YOLOU-main/utils/loss.py", line 1000, in __call__
    pi_aux = p[i + self.nl]
IndexError: list index out of range

**Comment by abcc235** [comment]
![image](https://user-images.githubusercontent.com/95196827/182095826-d01361bd-2773-47d9-b8e4-187b4976864c.png)
     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/190 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 771, in <module>
    main(opt)
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 669, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 447, in train
    loss, loss_items = compute_loss(pred, targets.to(device), imgs)  # init loss class
  File "/home/hanrenkun/F/test/YOLOU-main/utils/loss.py", line 1000, in __call__
    pi_aux = p[i + self.nl]
IndexError: list index out of range


Excuse me why

**Comment by dbzqyyy** [comment]
> ![image](https://user-images.githubusercontent.com/95196827/182095826-d01361bd-2773-47d9-b8e4-187b4976864c.png) Epoch gpu_mem box obj cls labels img_size 0%| | 0/190 [00:06<?, ?it/s] Traceback (most recent call last): File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 771, in main(opt) File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 669, in main train(opt.hyp, opt, device, callbacks) File "/home/hanrenkun/F/test/YOLOU-main/train.py", line 447, in train loss, loss_items = compute_loss(pred, targets.to(device), imgs) # init loss class File "/home/hanrenkun/F/test/YOLOU-main/utils/loss.py", line 1000, in **call** pi_aux = p[i + self.nl] IndexError: list index out of range
> 
> Excuse me why

excuse me, Have you fixed the problem?
