### ISSUE TITLE
yolov6s.pt这个文件不能加载，提示出错啊

### ISSUE THREAD

**Issue by douyu0814** [jizhishutong/YOLOU#36]
export: weights=['./weights/yolov6s.pt'], imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, dynamic=True, simplify=True, opset=12, include=['onnx']
YOLOv5  2022-8-25 Python-3.10.5 torch-1.12.0+cpu CPU

Traceback (most recent call last):
  File "E:\Code\YOLOU-main\export.py", line 209, in <module>
    main(opt)
  File "E:\Code\YOLOU-main\export.py", line 204, in main
    run(**vars(opt))
  File "E:\Code\pythonCode\changeable_region_detection-main\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\Code\YOLOU-main\export.py", line 133, in run
    model = attempt_load(weights, device=device, inplace=True, fuse=True)  # load FP32 model
  File "E:\Code\YOLOU-main\models\experimental.py", line 228, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "E:\Code\pythonCode\changeable_region_detection-main\venv\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\Code\pythonCode\changeable_region_detection-main\venv\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "E:\Code\pythonCode\changeable_region_detection-main\venv\lib\site-packages\torch\serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)

ModuleNotFoundError: No module named 'yolov6'

进程已结束,退出代码1

**Comment by gubei528** [comment]
我也遇到了这个问题，请问解决了吗
